# Домашнее задание "Линейная алгебра. Матрицы".

## Уровень 0:


### Задание 1

 - Создайте матрицу 3 на 3, заполненную числами от 1 до 9
 - Прибавьте к ней матрицу с единицами на диагонале
 - Умножьте полученную матрицу на вектор (1, 2, 3)
 - Вычислить транспонированную матрицу $A^T$ от полученной в результате прибавления матрицы
 - Посчитайте обратную матрицу к полученной в результате прибавления матрице


In [48]:
import numpy as np

# 1
my_matrix = np.random.randint(100, size=(3, 3))

# 2
sum_matrix = my_matrix + np.eye(3)

# 3
vector = [1, 2, 3]
mult_matrix = np.dot(sum_matrix, vector)
print(f"mult_vector: {mult_matrix}\n")

# 4
transp_matrix = np.transpose(sum_matrix)
print(f"transpose_matrix: {transp_matrix}\n")

# 5
reverse_matrix = np.linalg.inv(sum_matrix)
print(f"reverse_matrix: {reverse_matrix}\n")

mult_vector: [226. 100. 198.]

transpose_matrix: [[25. 89. 76.]
 [45.  1. 46.]
 [37.  3. 10.]]

reverse_matrix: [[-0.00110654  0.01082333  0.00084719]
 [-0.00572288 -0.02214807  0.02781908]
 [ 0.03473495  0.01962378 -0.03440645]]



## Уровень 1:

### Задание 2

Найдите собственные значения и собственные вектора матрицы:
```
m = np.array([[2, 2],
              [1, 3]])
print(m)
```



In [49]:
m = np.array([[2, 2],
              [1, 3]])

eig_values, eig_vectors = np.linalg.eig(m)
print(f"eig_values: {eig_values}\n")
print(f"eig_vectors: {eig_vectors}\n")

eig_values: [1. 4.]

eig_vectors: [[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]



### Задание 3


Придумайте матрицу, у которой определитель = 1, и все элементы не равны 0.

P.S. Матрица должна быть ненулевой и размерностью не менее 2! 

In [50]:
def matrix_2x2(det,a,b,c):
    d = (det + b * c) / a
    return np.array([[a, b], [c, d]])

matrix = matrix_2x2(1,2,3,1)
print(matrix)
print("matrix_determinant:", np.linalg.det(matrix))

[[2. 3.]
 [1. 2.]]
matrix_determinant: 1.0
